Schreyer Resolution over the exterior algebra
Singular/Singular pull request #1243
Opened 2024-08-08 11:18 UTC by Lax202

This draft is regarding my work on Schreyer resolutions of modules over the exterior algebra. @jankoboehm 

P.S. Note the proc sheafCohBGGsres takes really long but works.

2024-08-08 12:30 UTC, hannes14 commented on Singular/LIB/sresext.lib
> +    if (strv[sizev] == "2" && strw[sizew] == "2"){
lcm_ is static, i.e. only called in this library, ie.e. the base ring is a exterior algebra which cannot have squares.

2024-08-11 13:11 UTC, Lax202 commented on Singular/LIB/sresext.lib
> +    if (strv[sizev] == "2" && strw[sizew] == "2"){
lcm_ is used over the anti-commutative ring where xi xj = -xj xi. But this is used for very specific input. Either both terms come from the exterior algebra, in which case there are no squares, or there is one term that comes from the ideal of the exterior algebra and is thus a square of a variable, like x[2]^2.

2024-08-11 13:13 UTC, Lax202 commented on Singular/LIB/sresext.lib
> +    if (strv[sizev] == "2" && strw[sizew] == "2"){
Should I make comments that state which proc is working over the quotient ring ie the exterior algebra and which proc is over the anti-commutative ring?

2024-09-20 11:50 UTC, hannes14 requested changes
concerning documentation: avoid texinfo, trailing white spaces.

2024-09-20 11:50 UTC, hannes14 commented on Singular/LIB/sresext.lib
> +{"EXAMPLE:";
missing: echo2; after "EXAMPLE";

2024-09-20 11:50 UTC, hannes14 commented on Singular/LIB/sresext.lib
> +{"EXAMPLE:";
missing echo=2; after "EXAMPLE";

2024-09-20 11:50 UTC, hannes14 commented on Singular/LIB/sresext.lib
> +  intmat A=sheafCohBGG_sres(M,-9,4);
should be intmat A=sheafCohBGGsres(M,-9,4); ?
and takes too long (> 2min)

2024-09-20 11:50 UTC, hannes14 commented on Singular/LIB/sresext.lib
> +static proc mod_init()
please change the proc mod_init to
LIB "nctools.lib"; // for ncalg
LIB "matrix.lib"; // for submat
LIB "sheafcoh.lib"; // for displayCohom
```

2024-09-20 11:50 UTC, hannes14 commented on Singular/LIB/sresext.lib
> +  resoltuion temp_res = mresExt(EM,bound1+1);
resolution

2025-02-25 15:29 UTC, hannes14 approved these changes

2025-02-26 14:49 UTC, merged